"""Mailtrap SMTP daily digest — top articles from the last 24 hours."""
import smtplib
from datetime import datetime, timedelta, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from loguru import logger

from config.settings import settings
from src.storage.db import SessionLocal, get_pending_digest


def _build_html(articles) -> str:
    rows = ""
    for a in articles[:30]:
        inst = a.instruments or ""
        urgency_color = {
            1: "#e0e0e0", 2: "#90caf9", 3: "#fff176", 4: "#ffb74d", 5: "#ef5350"
        }.get(a.urgency or 1, "#fff")
        rows += f"""
        <tr>
          <td style="background:{urgency_color};text-align:center;font-weight:bold">{a.urgency}</td>
          <td><a href="{a.url}">{a.title[:90]}</a></td>
          <td>{a.event_type}</td>
          <td>{round(a.sentiment_compound or 0, 2):+}</td>
          <td style="font-size:11px">{inst[:50]}</td>
          <td style="font-size:11px">{a.source}</td>
        </tr>"""

    return f"""
    <html><body style="font-family:sans-serif">
    <h2>📊 Fintel Daily Digest — {datetime.now(timezone.utc).strftime('%Y-%m-%d')}</h2>
    <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;width:100%">
      <tr style="background:#263238;color:#fff">
        <th>U</th><th>Title</th><th>Type</th><th>Sent</th><th>Instruments</th><th>Source</th>
      </tr>
      {rows}
    </table>
    <p style="color:#999;font-size:11px">Generated by fintel-bot</p>
    </body></html>
    """


def send_digest() -> bool:
    if not settings.mail_password or not settings.digest_to_email:
        logger.warning("Mailtrap SMTP not configured (MAIL_PASSWORD or DIGEST_TO_EMAIL missing)")
        return False

    since = datetime.now(timezone.utc) - timedelta(hours=24)
    with SessionLocal() as session:
        articles = get_pending_digest(session, since)

    if not articles:
        logger.info("Digest: no articles to send")
        return False

    subject = f"Fintel Digest {datetime.now(timezone.utc).strftime('%Y-%m-%d')} — {len(articles)} alerts"
    html = _build_html(articles)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"{settings.mail_from_name} <{settings.mail_from_address}>"
    msg["To"] = settings.digest_to_email
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP(settings.mail_host, settings.mail_port) as server:
            server.ehlo()
            server.starttls()
            server.login(settings.mail_username, settings.mail_password)
            server.sendmail(settings.mail_from_address, settings.digest_to_email, msg.as_string())
        logger.info(f"Digest sent via Mailtrap SMTP: {len(articles)} articles")
        return True
    except Exception as e:
        logger.error(f"Mailtrap SMTP failed: {e}")
        return False
